/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.C_Pessoa;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Estevao
 */
public class V_Pessoa extends javax.swing.JFrame {

    /**
     * Creates new form V_Pessoa
     */
    C_Pessoa cPessoa = new C_Pessoa();
    ResultSet resultset;
    DefaultTableModel tabelaModelo = new DefaultTableModel();
    public V_Pessoa() {
        initComponents(); 
//        lb_id.setVisible(false);
        tabelaModelo.addColumn("Código");
        tabelaModelo.addColumn("Nome");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_nome = new javax.swing.JTextField();
        bt_salvar = new javax.swing.JButton();
        bt_pesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaResultados = new javax.swing.JTable();
        tf_pesquisa = new javax.swing.JTextField();
        lb_id = new javax.swing.JLabel();
        bt_excluir = new javax.swing.JButton();
        bt_atualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 38, 279, 86));

        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 160, -1, -1));

        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 38, -1, -1));

        tabelaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaResultados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 70, -1, 275));
        getContentPane().add(tf_pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 330, -1));
        getContentPane().add(lb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        bt_excluir.setText("Excluir");
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });
        getContentPane().add(bt_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        bt_atualizar.setText("Atualizar");
        bt_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        cPessoa.Conectar();
        cPessoa.Salvar(tf_nome.getText());
        cPessoa.Desconectar();
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
       while (tabelaModelo.getRowCount() > 0) {
                tabelaModelo.removeRow(0);
       }
        cPessoa.Conectar();
        resultset = cPessoa.Pesquisar(tf_pesquisa.getText());       
        try {
            while (resultset.next()) {
                tabelaModelo.addRow(new String[]{
                resultset.getString("pes_id"),
                resultset.getString("pes_nome")
                });
            }        
        tabelaResultados.setModel(tabelaModelo);
        } catch (SQLException ex) {
            Logger.getLogger(V_Pessoa.class.getName()).log(Level.SEVERE, null, ex);
        }
        cPessoa.Desconectar();
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void tabelaResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaResultadosMouseClicked
        lb_id.setText((String) tabelaResultados.getValueAt(
                tabelaResultados.getSelectedRow(), 0));
        tf_nome.setText((String) tabelaResultados.getValueAt(
                tabelaResultados.getSelectedRow(), 1));
    }//GEN-LAST:event_tabelaResultadosMouseClicked

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        cPessoa.Conectar();
        cPessoa.Deletar(Integer.parseInt(lb_id.getText()));
        cPessoa.Desconectar();
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarActionPerformed
        cPessoa.Conectar();
        cPessoa.Atualizar(Integer.parseInt(lb_id.getText()), tf_nome.getText());
        cPessoa.Desconectar();
    }//GEN-LAST:event_bt_atualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Pessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_id;
    private javax.swing.JTable tabelaResultados;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_pesquisa;
    // End of variables declaration//GEN-END:variables
}
